### ISSUE TITLE
названия

### ISSUE THREAD

**Issue by kuzmichevdima** [Sergmih/python-review#1]
https://github.com/Sergmih/python-review/blob/796b1d19951807a09a2c57c9f6a9567b8454282f/train.py#L6

https://github.com/Sergmih/python-review/blob/796b1d19951807a09a2c57c9f6a9567b8454282f/train.py#L31

https://github.com/Sergmih/python-review/blob/796b1d19951807a09a2c57c9f6a9567b8454282f/train.py#L33

здесь и далее - улучшить названия. func, str, lc, d, dict, tmp - ничего абсолютно не говорит

**Comment by Sergmih** [comment]
Исправил
