### ISSUE TITLE
random

### ISSUE THREAD

**Issue by kuzmichevdima** [Sergmih/python-review#11]
https://github.com/Sergmih/python-review/blob/f1916a55a1ac36e5d25108866bf180098c73c3fc/generate.py#L28-L34

заменить на numpy.random.choice, потому что это намного быстрее

**Comment by Sergmih** [comment]
сделал

**Comment by kuzmichevdima** [comment]
очень много ненужных действий в generate_text вот в этом куске кода:
https://github.com/Sergmih/python-review/blob/67cc0057b111858691075905a4fea417e0d4e195/generate.py#L36-L44

generation_list не нужен, это просто .keys()
frequency_list - это .values()
сумму, которая называется cnt (название сменить), можно посчитать в 1 строку с помощью опять же .values() и sum

**Comment by Sergmih** [comment]
переделал
