### ISSUE TITLE
вывод по 1 слову

### ISSUE THREAD

**Issue by kuzmichevdima** [Sergmih/python-review#13]
https://github.com/Sergmih/python-review/blob/67cc0057b111858691075905a4fea417e0d4e195/generate.py#L48
Во-первых, это медленно. Во-вторых, на выходе получается 1 супердлинная строка, а не текст

**Comment by Sergmih** [comment]
исправил

**Comment by kuzmichevdima** [comment]
где?
https://github.com/Sergmih/python-review/blob/20403e35556ff0b88734d845d9cfd0dffbc2126a/generate.py#L40-L41

**Comment by Sergmih** [comment]
забыл закомитить тогда. Переделал

**Comment by kuzmichevdima** [comment]
https://github.com/Sergmih/python-review/blob/adbe64f0370bb130e3304a931162a44f723d7ae1/generate.py#L42-L48

как это работает?
text же всегда равен current + пробел, или я чего-то не понимаю?

**Comment by kuzmichevdima** [comment]
https://github.com/Sergmih/python-review/blob/adbe64f0370bb130e3304a931162a44f723d7ae1/generate.py#L39-L41

так делать каждый раз - крайне медленно. Нужно предподсчитать заранее

**Comment by Sergmih** [comment]
то есть считать еще в train.py ?

**Comment by kuzmichevdima** [comment]
где считаешь нужным
