### ISSUE TITLE
model_dict

### ISSUE THREAD

**Issue by kuzmichevdima** [Sergmih/python-review#16]
https://github.com/Sergmih/python-review/blob/adbe64f0370bb130e3304a931162a44f723d7ae1/generate.py#L64
зачем эта строчка, если далее

https://github.com/Sergmih/python-review/blob/adbe64f0370bb130e3304a931162a44f723d7ae1/generate.py#L68

**Comment by Sergmih** [comment]
Действительно. Убрал
