### ISSUE TITLE
AttributeError

### ISSUE THREAD

**Issue by kuzmichevdima** [Sergmih/python-review#18]
python3 generate.py --model model --lenght 100

Traceback (most recent call last):
  File "generate.py", line 73, in <module>
    parser.parse_args().output, parser.parse_args().str_lenght)
  File "generate.py", line 36, in generate_text
    frequency_list = list(model_dict[current].value())
AttributeError: 'collections.defaultdict' object has no attribute 'value'

исправить

**Comment by Sergmih** [comment]
тогда еще вопрос, выходной файл указывается в формате output.txt или просто output , а .txt надо в проге дописать?

**Comment by Sergmih** [comment]
ой, я перепутал слегка

**Comment by Sergmih** [comment]
Исправил
