### ISSUE TITLE
Быстродействие

### ISSUE THREAD

**Issue by kuzmichevdima** [Sergmih/python-review#19]
https://github.com/Sergmih/python-review/blob/9195802293b700658d0d233b662d773fd91c3113/generate.py#L38-L43

лучше сделать список с текущими словами, потому что прибавлять к строке (+=) долго. Строка - immutable, поэтому при += создается новая с копированием из старой. Тогда и длину не нужно будет поддерживать в отдельной переменной

**Comment by Sergmih** [comment]
переделал
