### ISSUE TITLE
комментарии

### ISSUE THREAD

**Issue by kuzmichevdima** [Sergmih/python-review#4]
https://github.com/Sergmih/python-review/blob/796b1d19951807a09a2c57c9f6a9567b8454282f/train.py#L48

https://github.com/Sergmih/python-review/blob/796b1d19951807a09a2c57c9f6a9567b8454282f/train.py#L16

Комментарии не нужно оставлять для галочки. Те, что есть у тебя сейчас, абсолютно ничего не проясняют. Либо действие очевидно, и комментировать его не нужно, либо надо писать понятное сообщение.

**Comment by kuzmichevdima** [comment]
нет. Почитай, как должны быть оформлены комменты по code style. Должны быть описания аргументов и того, что возвращает функция

**Comment by Sergmih** [comment]
переделал
