### ISSUE TITLE
копипаст

### ISSUE THREAD

**Issue by kuzmichevdima** [Sergmih/python-review#9]
https://github.com/Sergmih/python-review/blob/f1916a55a1ac36e5d25108866bf180098c73c3fc/train.py#L33-L38

https://github.com/Sergmih/python-review/blob/f1916a55a1ac36e5d25108866bf180098c73c3fc/train.py#L44-L47

копипаст

**Comment by Sergmih** [comment]
Да, копипаст. Но я не знаю как это можно записать короче, ведь во втором случае мы пробегаемся по всем файлам в директории и собираем текст из каждого, а в первом случае всего один раз запускаемся

**Comment by kuzmichevdima** [comment]
так что, фикса нет, а дедлайн прошел

**Comment by Sergmih** [comment]
исправил

**Comment by Sergmih** [comment]
переделал
